### ISSUE TITLE
Вертска секции абонементов

### ISSUE THREAD

**Issue by catch-a-chalk** [catch-a-chalk/1872127-fitness#1]
Нашел два варианта на чистом JS. Подскажи, какой из них выбрать:
https://webdesign.tutsplus.com/ru/tutorials/how-to-build-a-responsive-tab-component-with-css-and-a-touch-of-javascript--cms-30456
https://codepen.io/Jake_Woods/pen/vYYoYxo

**Comment by baileys-li** [comment]
Если бы я делал для себя, то смотрел бы [сюда](https://web-standards.ru/articles/tabbed-interfaces/). Потому что упор на доступность.

А уж какие-то мелочи, типо с какой анимацией переключаются, не очень имеют значение, кмк
