### ISSUE TITLE
Верстка секции карусели (тренеры, отзывы)

### ISSUE THREAD

**Issue by catch-a-chalk** [catch-a-chalk/1872127-fitness#2]
Пока не расширял до требуемого количества, пока нет определенности с подходом (8 карточек тренеров и две за отзывы). Также нашел вариант для реализации:
https://html5css.ru/howto/howto_js_slideshow.php?ysclid=l8k57j3st7719262883

**Comment by baileys-li** [comment]
Этот вариант не надо. Сам сайт выглядит устаревшим. 

Давай сделаем, как сделали бы в реальный проектах — возьмем популярный пакет. Предлагаю, [Swiper](https://swiperjs.com/)

Я могу показать несколько вариантов с кастомными каруселями, но пока лучше остановится на билблиотеке. Потому что я сам не уверен что готов учесть все нюансы.

**Comment by catch-a-chalk** [comment]
Была попытка реализовать карусель, но не понял принцип работы; расставил классы. Академией в сборке уже предусмотрены скрипты от свайпера, есть ли смысл писать отдельный файл init-swiper?

И как будем прописывать дополнительные блоки для отображения? Внутри pug-файла в перечислении данных констант?
