### ISSUE TITLE
Стилизация тега <iframe> в блоке о зале

### ISSUE THREAD

**Issue by catch-a-chalk** [catch-a-chalk/1872127-fitness#3]
Нашел вопросник на хабре, но ни одно из решений не понял каким образом должно мне помочь. Как я могу поставить макетные фото и иконку проигрывания на превью?

**Comment by baileys-li** [comment]
А что ты хочешь в iframe засунуть? Видео ютуба? 

Стилизовать никак.
Давай сделаем [по примеру](https://youtu.be/4JS70KB9GS0) Макеева. Т.е. верстаем свой элемент, а по клику оно подменяется на iframe нужного хостинга

**Comment by catch-a-chalk** [comment]
Сделал все как по видео, но есть, как минимум, проблема с путями к изображению, просьба посмотреть скрипт

**Comment by baileys-li** [comment]
@catch-a-chalk погоди, у тебя видео обложки есть в макете. Скрипты по тому как брать их из ютуба не нужно повторять

**Comment by baileys-li** [comment]
https://github.com/baileys-li/sedona-adaptive/blob/master/source/javascript/video.js

**Comment by baileys-li** [comment]
Не помешало бы у iframe убрать рамку
