### ISSUE TITLE
Иконки соцсетей в футере

### ISSUE THREAD

**Issue by catch-a-chalk** [catch-a-chalk/1872127-fitness#6]
Как я могу через фигму вырезать иконки таким образом, чтобы был доступен белый круг с прозрачным логотипом? Иначе при смене бекграунда смотреться будет так себе

**Comment by baileys-li** [comment]
Вырезать одно из другого в локальной копии
![image](https://user-images.githubusercontent.com/47776594/193644068-14d1ed08-7173-4177-80c8-6f3d807db9d4.png)
