### ISSUE TITLE
Блок с абонементами

### ISSUE THREAD

**Issue by catch-a-chalk** [catch-a-chalk/1872127-fitness#9]
Основной вопрос: отображение знака рубля и корректное написание стилей для тени. По первому: в библиотеке полезных материалов есть ссылка на статью Лебедева, но она очень старая и формат шрифта предлагается OpenType, да и зачем его использовать, если Академией уже интегрирован шрифт rouble.woff2 в самом начале? Не смог только разобарться как достать заветный знак из него.

**Comment by baileys-li** [comment]
В спрайт
